config/routes.rb
Rails.application.routes.draw do
  get 'open_files/index'
  resources :words
  devise_for :users
  root "comments#index"

  resources :comments
  resources :words, controller: 'words', as: 'admin_words'

  get '/comment_show', to: 'comments#show_result', as: 'comment_show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  require "open-uri"

  def index; end

  def new
    @comment = Comment.new
  end

  def create
    #ebay
    if current_user
      @id_ebay = ""
      if (comments_params["url"].include? "ebay.com/p/")
        @id_ebay = id_first_method(comments_params["url"])
      elsif (comments_params["url"].include? "ebay.com/urw/")
        @id_ebay = id_second_method(comments_params["url"])
      end
      @comments_count = put_pages_count(@id_ebay)/10


      i = 1
      @comment = ""
      @comment_title = ""
      url = Nokogiri::HTML(open("https://www.ebay.com/urw/shrek-love-/product-reviews/#{@id_ebay}?pgn=1"))
      puts(url.css("p.review-item-content"))
      @test = url.css("p.review-item-content").to_s
      if @test == ""
        redirect_to new_comment_path
      else
      while @comments_count + 1 != i
        puts(i)
        url = Nokogiri::HTML(open("https://www.ebay.com/urw/shrek-love-/product-reviews/#{@id_ebay}?pgn=#{i}"))
        puts ("https://www.ebay.com/urw/shrek-love-/product-reviews/#{@id_ebay}?pgn=#{i}")

        url.css("p.review-item-content").each do |link|
          @comment += link.content + " /*/ "
        end

        i += 1
      end


      $comment = @comment.split(" /*/ ")

      #analyzer
      analyzer = Sentimental.new
      analyzer.load_defaults
      analyzer.threshold = 0.1
      my_hash = []
      @sentiment = ""
      @score = ""
      $comment.each_with_index do |comment, i|
        @sentiment += (analyzer.sentiment comment).to_s + "/*/"
        @score += (analyzer.score comment).to_s + "/*/"
        sentiment = analyzer.sentiment comment
        score = analyzer.score comment
        my_hash << {comment: "#{comment}",score: "#{score}", sentiment: "#{sentiment}"}
      end
      $sentiment = @sentiment.split("/*/")
      puts ($sentiment)
      $score = @score.split("/*/")
      puts $score

      $comment_json = my_hash.to_json
      # puts $comment_json
      # $graph_array = []
      # $graph_array << {sentiment: "positive", count: "#{$sentiment.count("positive")}"}
      # $graph_array << {sentiment: "negative", count: "#{$sentiment.count("negative")}"}
      # $graph_array << {sentiment: "neutral", count: "#{$sentiment.count("neutral")}"}
      # $graph_array << {"positive": $sentiment.count("positive"), "negative": $sentiment.count("negative"), "neutral": $sentiment.count("neutral")}
      # $graph_array << {"negative": $sentiment.count("negative")}
      # $graph_array << {"neutral": $sentiment.count("neutral")}

      # puts $graph_array
      # if File.exist?('./file.json')
      #   File.delete("./file.json")
      # end
      # File.open('./file.json', 'w') do |f|
      #   f.write($comment_json.to_json)
      # end
      redirect_to comment_show_path
    end
    else
      redirect_to new_user_registration_path
    end

    def show_result
      $graph_array = []
      $graph_array << "positive"
      $graph_array << $sentiment.count("positive")
      $graph_array2 = []
      $graph_array2 << "negative"
      $graph_array2 << $sentiment.count("negative")
      $graph_array3 = []
      $graph_array3 << "neutral"
      $graph_array3 << $sentiment.count("neutral")
      #, "negative": $sentiment.count("negative"), "neutral": $sentiment.count("neutral")
      # $graph_array = $graph_array.to_h
      puts $graph_array

    end
    #parse rozetka
    # if current_user
      # if File.exist?('./file.txt')
      #   File.delete("./file.txt")
      # end
    #   @sum = 0
    #   file = File.new("./file.txt", "a:UTF-8")
    #   rate_word = Word.all
    #   id = comments_params["url"].match("p[0-9]+").to_s.gsub(/p/, '')
    #   puts(id)
    #   site = HTTParty.get("https://product-api.rozetka.com.ua/v3/comments/get?front-type=xl&goods=#{id}&page=1&sort=date&limit=10&lang=ru")
    #   site = site.parsed_response.to_json
    #   data_hash = JSON.parse(site)
    #   page = count = data_hash["data"]["pages"]["count"]
    #   i = 2
    #   while page + 1 != i
    #     site = HTTParty.get("https://product-api.rozetka.com.ua/v3/comments/get?front-type=xl&goods=#{id}&page=#{i}{}&sort=date&limit=10&lang=ru")
    #     site = site.parsed_response.to_json
    #     data_hash = JSON.parse(site)
    #     puts i
    #     data_hash["data"]["comments"].each do |comment|
    #       comment = comment['text'].downcase
    #       word = comment.split(" ")
    #       puts comment
    #       @sum = 0
    #       rate_word.each do |rate|
    #         if (comment.include? rate.word.to_s)
    #           if rate.rate
    #             @sum += 1
    #             puts rate.rate
    #           else
    #             puts rate.rate
    #             @sum -= 1
    #           end
    #         end
    #       end
    #       file.write("#{comment}, Оцінка:   #{@sum}   ||   \n\r")
    #     end
    #     i += 1
    #   end
    #   redirect_to open_files_index_path
    # else
    #   redirect_to new_user_registration_path
    # end
  end

  def put_pages_count(id)
    url = Nokogiri::HTML(open("https://www.ebay.com/urw/shrek-love-/product-reviews/#{id}?pgn=1"))
    comments_count = url.css("h2.reviews-section-title").text
    comments_count = comments_count.split(" ")
    comments_count = comments_count[0]
    comments_count = round(comments_count.to_i)
    return comments_count
  end

  def id_first_method(url)
    tmp = url.split("/")
    id_ebay = tmp[4].split("?")
    id_ebay = id_ebay[0]
    return id_ebay
  end

  def id_second_method(url)
    tmp = url.split("/")
    tmp = tmp[6].split("?")
    id_ebay = tmp[0]
    return id_ebay
  end

  def round(n)
    (n+10)/10*10
  end

  private

  def comments_params
    params.require(:comment).permit(:url)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  def index
    @words = Word.all
  end

  def show; end

  def new
    @word = Word.new
  end

  def edit; end

  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_word
      @word = Word.find(params[:id])
    end

    def word_params
      params.require(:word).permit(:word, :rate)
    end

    def authorize_admin
      if !(current_user && current_user.admin == true)
        redirect_to comments_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/comments/index.html.erb
<div class="jumbotron jumbotron-inverse jumbotron-hero market-ua" style="background-image: url(https://i.imgur.com/tlZxlkq.jpg)">
    <div class="container">
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-10 col-lg-offset-1">
          <h1> Сервіс aналізу тональності тексту </h1>
          <h4>Tonalyze</h4>
        </div>
      </div>
    </div>
  </div>
  <hr class= "color">
  <hr class= "color1">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <br>
  <br>
  <br>
<div class="text-center container ">
    <h2>На даному сайті є можливість проаналізувати відгуки з інтернет магазину Ebay, натиснувши на кнопку нижче, ви перейдете до форми, куди треба вставити посилання на товар. </h2>
    <div class="col-12">
        <%= link_to "Передача посилання на аналіз", new_comment_path, class:"btn btn-dark btn-lg btn-block color1" %>
    </div>
 </div>
<br>
<br>
<br>
<br>
<br>

app/views/comments/new.html.erb
<hr class= "color">
<hr class= "color1">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

  <%= form_with(model: @comment, local: true) do |form| %>
  <div class="text-center container">
    <br><br><br><br>
    <h2>Посилання повинне бути такого типу: https://www.ebay.com/urw/назва_товару-/product-reviews/******* або https://www.ebay.com/p/*******?iid=*********</h2>
    <br><br>
    <div class = "field">
      <%= form.text_field :url, class: "form-control", placeholder: "Введіть посилання!"%>
    </div>
    <br>
    <div class="actions">
      <div class="form-row text-center" style="">
         <div class="col-12">
            <%= form.submit :"Зробити аналіз", class: "btn btn-dark btn-lg btn-block color1"  %>
         </div>
      </div>
    </div>
  </div>
  <% end %>
  <br><br><br><br><br><br><br><br><br><br>

app/views/comments/show_result.html.erb
<hr class= "color">
<hr class= "color1">
<br><br><br>
<%= pie_chart [$graph_array, $graph_array2, $graph_array3] %>
<div class="container list-group-item ">
  <table class="table">
    <tr>
      <td><h5><b>Відгук</b></h5></td>
      <td></td>
      <td><h5><b>Оцінка</b></h5></td>
      <td></td>
      <td><h5><b>Емоційне забарвлення</b></h5></td>
    </tr>

  <% $comment.each_with_index do |comment, i| %>
    <tr>
      <td><%= comment %><td>
      <td id = "score"><%= $score[i] %><td>
      <td><%= $sentiment[i] %><td>
    <tr>
  <% end %>
  </table>
</div>
<br><br><br><br><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiplomaWork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src = "https://kit.fontawesome.com/ac7c51298a.js" crossorigin = "anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiplomaWork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.erb
<hr class= "color1">
<hr class= "color">
<br>

<div class = "footer-copyright text-center py-3 ">© 2020 Tonalyze:
  <strong>RoR</strong><br><br><br>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark h-30 color1">
  <%= link_to "Tonalyze", root_path, class: "navbar-brand "%>

  <ul class="nav navbar-nav ml-auto white">
    <% if current_user %>
      <li class="nav-item white">
        <a class="nav-link white" href="#"><span class="fas fa-user white"></span><%= current_user.email %></a>
      </li>
      <li class="nav-item">
        <a><%= link_to "Вихід", destroy_user_session_path, method: :delete, class: "nav-link white" %></a>
      </li>
      <% if current_user.admin? %>
         <a ><%= link_to "Адмінка", words_path, class: "nav-link white" %></a>
       <% end %>

    <% else %>
      <li class="nav-item">
        <a><%= link_to "Увійти в систему", new_user_session_path, class: "nav-link white"%></a>
      </li>
      <li class="nav-item">
        <a style="color:white"><%= link_to "Реєстрація", new_user_registration_path, class: "nav-link white" %></a>
      </li>
    <% end %>
  </ul>
</nav>

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
        <% word.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Слово" %>
    <%= form.text_field :word %>
  </div>

  <div class="field">
    <%= form.label :"Оцінка" %>
    <%= form.check_box :rate %>
  </div>

  <div class="actions">
    <%= form.submit :"Підтвердити", class:"btn btn-success" %>
  </div>
<% end %>

app/views/words/edit.html.erb
<div class="text-center container">
  <h1>Редагування слова</h1>

  <%= render 'form', word: @word %>

  <%= link_to 'Повернутись назад', words_path, class:"btn btn-danger" %>
</div>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Слова</h1>
<hr>
<%= link_to 'Додати нове слово', new_word_path, class:"btn btn-primary bg-md" %>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Слово</th>
      <th>Оцінка (позитив/негатив)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= word.rate %></td>
        <td><%= link_to 'Відредагувати', edit_word_path(word), class:"btn btn-warning bg-md" %></td>
        <td><%= link_to 'Видалити', word, method: :delete, data: { confirm: 'Ви впевнені?' }, class:"btn btn-danger bg-md" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/words/new.html.erb
<div class="text-center container">
  <h1>Додавання нового слова</h1>

  <%= render 'form', word: @word %>

  <%= link_to 'Повернутись назад', words_path, class:"btn btn-danger" %>
</div>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @word.rate %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>